name: Hackney.Core.Sns-publish
on:
  push:
    branches:
    - release
    - feature/**
    paths:
      - "Hackney.Core.Sns/**"
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine package version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display package version
        run: |
          echo "Version: $GITVERSION_NUGETVERSIONV2"
  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      VERSION: ${{ needs.calculate-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Package
        run: dotnet pack Hackney.Core.Sns -p:PackageVersion=$VERSION --configuration Release
      - name: Publish the Package
        run: |
          cd Hackney.Core.Sns/bin/Release
          dotnet nuget push Hackney.Core.Sns.*.nupkg -s https://nuget.pkg.github.com/LBHackney-IT/index.json --api-key ${{secrets.NUGET_KEY }}